version: "3"
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/pwa-test
    working_dir: /var/www/pwa-test
    user: "1000:1000"
    depends_on:
      - database
  node:
    container_name: node
    tty: true
    image: node:20-alpine
    volumes:
      - ./app:/var/www/pwa-test
    working_dir: /var/www/pwa-test
    command: npm run watch
    depends_on:
      - database
      - php
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/pwa-test
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
      - node
